[package]
name = "toolapi"
version = "0.1.1"
edition = "2024"

license-file = "LICENSE"
description = "MRX ToolAPI - connect clients and tools running in the cloud."
homepage = "https://mrx-org.github.io/mrx-book/"
repository = "https://github.com/mrx-org/toolapi"
readme = "README.md"
keywords = []
categories = []

[dependencies]
# For using secure websockets (wss://), tungstenite needs a TLS lib enabled.
# On fly.io, native-tls crashes on debian:bookworm-slim (libssl.so.3 not found).
# herefore we define tungstenite explicitly and enable its rustls feature.
rustls = { version = "0.23", features = ["ring"], default-features = false }
tungstenite = { version = "0.28.0", features = ["rustls-tls-webpki-roots"] }
tokio-tungstenite = { version = "0.28.0", features = ["rustls-tls-webpki-roots"] }
axum = { version = "0.8.8", features = ["ws"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
thiserror = "2.0.18"
num-complex = { version = "0.4.6", features = ["serde"] }
rmp-serde = "1.3.1"
