[package]
name = "toolapi"
version = "0.1.0"
edition = "2024"

[dependencies]
# For using secure websockets (wss://), tungstenite needs a TLS lib enabled.
# On fly.io, native-tls crashes on debian:bookworm-slim (libssl.so.3 not found).
# herefore we define tungstenite explicitly and enable its rustls feature.
rustls = { version = "0.23", features = ["ring"], default-features = false }
tungstenite = { version = "0.28.0", features = ["rustls-tls-webpki-roots"] }
tokio-tungstenite = { version = "0.28.0", features = ["rustls-tls-webpki-roots"] }
axum = { version = "0.8.8", features = ["ws"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
num-complex = { version = "0.4.6", features = ["serde"] }
